language: objective-c
osx_image: xcode8

branches:
 only:
 - master

script:
- set -o pipefail && xcodebuild -workspace Keith.xcworkspace -scheme Keith -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' build test | xcpretty --color
